### Prueba
GET http://localhost:3000/
### Enviar equipos
POST http://localhost:3000/teams
Content-Type: application/json

{
  "teams":{
    "firstTeam": ["Luis", "Maria", "Carlos", "Ana", "Pedro"],
    "secondTeam": ["Laura", "José", "Sofía", "Miguel", "Elena"]
  },
  "category": "Fútbol 5"
}

### Obtener equipos
GET http://localhost:3000/teams




### Enviar equipos
POST http://localhost:3000/teams
Content-Type: application/json

{
  "teams":{
    "firstTeam": ["pepe", "juan", "lu", "bauti", "frank"],
    "secondTeam": ["rod", "jonny", "ger", "leo", "mateo"]
  },
  "category": "Fútbol 7"
}




